sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t timbedsted1234/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timbedsted1234/docker-react npm run test
